name: CI Workflow

on:
  push:
    branches:
      - devops-workflow
    
jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      #- name: Set up Node.js 
        #uses: actions/setup-node@v3
        #with:
          #node-version: '18.12'

      - name: Install Dependencies
        run: npm ci --verbose --frozen-lockfile

      #- name: Verify dependencies
        #run: npm audit

      - name: Build application
        run: npm run build

      - name: Install Vercel CLI
        run: npm install -g vercel@25.1.0
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./